---
title: Personal Blog
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  github:
    title: Projects
    output: true
    permalink: "/projects"
  uploads:
    title: Uploads
    output: true
